# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='文章名称')),
                ('author', models.CharField(blank=True, default='admin', max_length=20, null=True, verbose_name='作者')),
                ('amount', models.IntegerField(blank=True, default=1, null=True, verbose_name='访问量')),
                ('content', models.TextField(verbose_name='文章内容')),
            ],
            options={
                'verbose_name_plural': '5-文章信息',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机')),
                ('company', models.CharField(max_length=128, null=True, verbose_name='公司')),
                ('department', models.CharField(max_length=64, null=True, verbose_name='部门')),
                ('position', models.CharField(max_length=64, null=True, verbose_name='职位')),
                ('interest', models.CharField(max_length=256, null=True, verbose_name='兴趣')),
                ('opinion', models.TextField(null=True, verbose_name='意见')),
                ('creat_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '6-加入我们信息',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='域名名称')),
                ('url', models.URLField(max_length=128, verbose_name='域名地址')),
            ],
            options={
                'verbose_name_plural': '1-域名管理',
            },
        ),
        migrations.CreateModel(
            name='Imgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True, verbose_name='标题')),
                ('content', models.TextField(null=True, verbose_name='文本')),
                ('url', models.CharField(blank=True, max_length=256, null=True, verbose_name='链接')),
                ('img', models.CharField(max_length=255, verbose_name='图片')),
            ],
            options={
                'verbose_name_plural': '5-图片信息',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField(default=1, verbose_name='权重')),
                ('name', models.CharField(max_length=64, verbose_name='库名称')),
                ('width', models.CharField(blank=True, default='100%', max_length=10, null=True, verbose_name='宽度')),
                ('height', models.CharField(blank=True, default='100%', max_length=10, null=True, verbose_name='高度')),
                ('space', models.IntegerField(blank=True, default=10000000, null=True, verbose_name='空间')),
            ],
            options={
                'verbose_name_plural': '3-模板库',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='页面名称')),
                ('url', models.CharField(max_length=256, verbose_name='链接')),
            ],
            options={
                'verbose_name_plural': '4-用户页面管理',
            },
        ),
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='模板名称')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitc.Domain')),
            ],
            options={
                'verbose_name_plural': '2-模板类型',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('ename', models.CharField(max_length=128, null=True, verbose_name='姓名拼音')),
                ('company', models.CharField(max_length=128, null=True, verbose_name='公司名称')),
                ('position', models.CharField(max_length=128, null=True, verbose_name='职位')),
                ('pic', models.CharField(max_length=256, null=True, verbose_name='头像')),
                ('summary', models.TextField(null=True, verbose_name='简介')),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitc.Page')),
            ],
            options={
                'verbose_name_plural': '5-人员信息',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='标题')),
                ('url', models.CharField(max_length=128, verbose_name='视频地址')),
                ('vl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitc.Page')),
            ],
            options={
                'verbose_name_plural': '5-视频信息',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='pp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitc.PageTemplate'),
        ),
        migrations.AddField(
            model_name='library',
            name='ptl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitc.PageTemplate'),
        ),
        migrations.AddField(
            model_name='imgs',
            name='il',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitc.Page'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set([('name', 'phone')]),
        ),
        migrations.AddField(
            model_name='article',
            name='al',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitc.Page'),
        ),
    ]
