# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='插件名称')),
                ('table', models.CharField(max_length=64, verbose_name='表名称')),
            ],
            options={
                'verbose_name_plural': '3-插件库',
            },
        ),
        migrations.AddField(
            model_name='library',
            name='plugin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gitc.Plugin'),
            preserve_default=False,
        ),
    ]
