# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitc', '0003_pagetemplate_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Html',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('url', models.CharField(default='templates/', max_length=255, verbose_name='本地地址')),
                ('hp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitc.Page')),
            ],
        ),
    ]
