# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitc', '0004_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gitc.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='html',
            name='hl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gitc.Library'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imgs',
            name='ip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gitc.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='ppl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gitc.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='vp',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='gitc.Page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='al',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitc.Library'),
        ),
        migrations.AlterField(
            model_name='imgs',
            name='il',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitc.Library'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='pl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitc.Library'),
        ),
        migrations.AlterField(
            model_name='video',
            name='vl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitc.Library'),
        ),
    ]
