# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-31 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitc', '0005_auto_20170729_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.CharField(max_length=20, null=True, verbose_name='作者'),
        ),
    ]
