# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-31 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitc', '0006_article_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(max_length=255, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.CharField(max_length=20, null=True, verbose_name='缩略图'),
        ),
    ]
